defaults: &defaults
  :cs_api:
    :challenges: 'http://cs-api-sandbox.herokuapp.com/v1/challenges'
    :members: 'http://cs-api-sandbox.herokuapp.com/v1/members'
  :expiry: 5
  :s3:
    :key: "key"
    :secret: "secret"
    :bucket: "bucket-for-cloudspokes-assets"
  :access_token: "ACCESS_TOKEN"

development:
  <<: *defaults

test:
  <<: *defaults

production:
  <<: *defaults